{% set name = "libml_dtypes-headers" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jax-ml/ml_dtypes/archive/v{{ version }}.tar.gz
  sha256: d505395b57656b543933bb4b3238a83036a17d4e8a5f36b58a0991093a184ade

build:
  number: 0
  noarch: generic

requirements:
  run:
    - __unix  # [unix]
    - __win  # [win]

test:
  commands:
    - test -f ${PREFIX}/include/ml_dtypes/include/float8.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\ml_dtypes\include\float8.h (exit 1)  # [win]


about:
  home: https://github.com/jax-ml/ml_dtypes
  summary: A stand-alone implementation of several NumPy dtype extensions used in machine learning.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
