{% set name = "libml_dtypes-headers" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jax-ml/ml_dtypes/archive/v{{ version }}.tar.gz
  sha256: cb38843a9802bad96d333de257edd68e834f5db0db812a6218589535bf56c3a3

build:
  number: 0
  noarch: generic

requirements:
  run:
    - __unix  # [unix]
    - __win  # [win]

test:
  commands:
    - test -f ${PREFIX}/include/ml_dtypes/include/float8.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\ml_dtypes\include\float8.h (exit 1)  # [win]


about:
  home: https://github.com/jax-ml/ml_dtypes
  summary: A stand-alone implementation of several NumPy dtype extensions used in machine learning. 
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
