{% set name = "libml_dtypes-headers" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jax-ml/ml_dtypes/archive/v{{ version }}.tar.gz
  sha256: f50ed095a4c262b2d4cddc9ec22fc571b698f37008f12ea62e17a7ea43c7b458

build:
  number: 0

test:
  commands:
    - test -f ${PREFIX}/include/ml_dtypes/include/float8.h  # [unix]
    - test -f ${PREFIX}/include/ml_dtypes/include/int4.h    # [unix]
    - test -f ${PREFIX}/include/ml_dtypes/include/intn.h    # [unix]
    - if not exist %LIBRARY_PREFIX%\include\ml_dtypes\include\float8.h (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\include\ml_dtypes\include\int4.h (exit 1)    # [win]
    - if not exist %LIBRARY_PREFIX%\include\ml_dtypes\include\intn.h (exit 1)    # [win]


about:
  home: https://github.com/jax-ml/ml_dtypes
  summary: A stand-alone implementation of several NumPy dtype extensions used in machine learning.
  description: A stand-alone implementation of several NumPy dtype extensions used in machine learning.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/jax-ml/ml_dtypes
  doc_url: https://github.com/jax-ml/ml_dtypes

extra:
  skip-lints:
    - missing_section
  recipe-maintainers:
    - xhochy
